### ISSUE TITLE
ImportError: cannot import name 'EpollSelector' from 'selectors' 

### ISSUE THREAD

**Issue by showlrr** [thunlp/OpenPrompt#117]
(openPrompt_env2) D:\code_run\OpenPrompt>python sample.py
Traceback (most recent call last):
  File "sample.py", line 3, in <module>
    from openprompt.data_utils import InputExample
  File "D:\code_run\OpenPrompt\openprompt\__init__.py", line 4, in <module>
    from .trainer import ClassificationRunner, GenerationRunner
  File "D:\code_run\OpenPrompt\openprompt\trainer.py", line 23, in <module>
    from openprompt.prompts import *
  File "D:\code_run\OpenPrompt\openprompt\prompts\__init__.py", line 22, in <module>
    from .generation_verbalizer import GenerationVerbalizer
  File "D:\code_run\OpenPrompt\openprompt\prompts\generation_verbalizer.py", line 3, in <module>
    from selectors import EpollSelector
ImportError: cannot import name 'EpollSelector' from 'selectors' (D:\tool\anaconda\envs\openPrompt_env2\lib\selectors.py)

**Comment by kingdawei** [comment]
I pip installed selectors and it worked.

**Comment by kingdawei** [comment]
Were you able to solve this?
