### ISSUE TITLE
Demo_step6_WrapperClass_Error

### ISSUE THREAD

**Issue by pan000987** [thunlp/OpenPrompt#128]
## 环境：
win10, openpropt==0.1.1，python==3.7, tensorflow==2.8, torch==1.11.0, transformers==4.17.0,  torchvision==0.12
## 修改操作：
我使用了demo,其中在step2，将bert-base-cased修改为了huggingface的中文包:
>config.json
flax_model.msgpack
pytorch_model.bin
tokenizer.json
tokenizer_config.json
vocab.txt

## 问题：
在Step6中的PromptDataLoader方法的调用中，*tokenizer_wrapper_class=WrapperClass,*出现如下报错
>Traceback (most recent call last):
  File "D:/2-working/auto_marking_machine/prompt learning/processing_data.py", line 66, in <module>
    tokenizer_wrapper_class=WrapperClass,
  File "D:\01-Course\Anaconda\envs\auto_marking_machine\lib\site-packages\openprompt\pipeline_base.py", line 90, in __init__
    self.wrap()
  File "D:\01-Course\Anaconda\envs\auto_marking_machine\lib\site-packages\openprompt\pipeline_base.py", line 115, in wrap
    wrapped_example = self.template.wrap_one_example(example)
  File "D:\01-Course\Anaconda\envs\auto_marking_machine\lib\site-packages\openprompt\prompt_base.py", line 199, in wrap_one_example
    text = self.incorporate_text_example(example)
  File "D:\01-Course\Anaconda\envs\auto_marking_machine\lib\site-packages\openprompt\prompt_base.py", line 104, in incorporate_text_example
    text[i] = d["add_prefix_space"] + d.get("post_processing", lambda x:x)(getattr(example, d['placeholder']))
TypeError: can only concatenate str (not "float") to str

## 自查 
WrapperClass 为MLMTokenizerWrapper类， 但是再往下的怎么修改就不清楚了。

## 请帮忙看下，万分感谢。

**Comment by ShengdingHu** [comment]
We write a [tutorial](https://github.com/thunlp/OpenPrompt/blob/main/tutorial/6.1_chinese_dataset_uer_t5.py) to show the use case that does not fit into the default configuration of OpenPrompt. With  slight change to the tokenizer_wrapper, you can handle such kind of tasks. More specifically,  in this tutorial, we use a bert tokenizer and a T5 model to do a Chinese Classic Poetry Retrieval task. Thanks for posing this issue!
