### ISSUE TITLE
Met bug in running tutorial 2.2_conditional_generation.py

### ISSUE THREAD

**Issue by xikaluo** [thunlp/OpenPrompt#137]
Hello, today I met an error in running the code copied from tutorial/2.2_conditional_generation.py. Looks like the problem is due to some mismatching between openprompt and torch? Thank you.

Error report:
Traceback (most recent call last):
  File "temp_use.py", line 153, in <module>
    generated_sentence = evaluate(prompt_model, test_dataloader)
  File "temp_use.py", line 108, in evaluate
    _, output_sentence = prompt_model.generate(inputs, **generation_arguments)
  File "/Users/chenyizhou/opt/anaconda3/envs/open_prompt/lib/python3.8/site-packages/openprompt/pipeline_base.py", line 471, in generate
    output_sequences = super().generate(**batch, **input_generation_kwargs, pad_token_id=self.tokenizer.pad_token_id, eos_token_id=self.tokenizer.eos_token_id)
  File "/Users/chenyizhou/opt/anaconda3/envs/open_prompt/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/chenyizhou/opt/anaconda3/envs/open_prompt/lib/python3.8/site-packages/transformers/generation_utils.py", line 1083, in generate
    inputs_tensor, model_input_name, model_kwargs = self._prepare_model_inputs(inputs, bos_token_id, model_kwargs)
  File "/Users/chenyizhou/opt/anaconda3/envs/open_prompt/lib/python3.8/site-packages/transformers/generation_utils.py", line 401, in _prepare_model_inputs
    input_name = self.main_input_name
  File "/Users/chenyizhou/opt/anaconda3/envs/open_prompt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'PromptForGeneration' object has no attribute 'main_input_name'

Environment: 
openprompt==0.1.2
torch==1.11.0
no gpu (use_gpu==False)
arguments: Namespace(lr=5e-05, model='t5', model_name_or_path='t5-base', plm_eval_mode=False)

**Comment by ningding97** [comment]
> Hello, today I met an error in running the code copied from tutorial/2.2_conditional_generation.py. Looks like the problem is due to some mismatching between openprompt and torch? Thank you.
> 
> Error report: Traceback (most recent call last): File "temp_use.py", line 153, in generated_sentence = evaluate(prompt_model, test_dataloader) File "temp_use.py", line 108, in evaluate _, output_sentence = prompt_model.generate(inputs, **generation_arguments) File "/Users/chenyizhou/opt/anaconda3/envs/open_prompt/lib/python3.8/site-packages/openprompt/pipeline_base.py", line 471, in generate output_sequences = super().generate(**batch, **input_generation_kwargs, pad_token_id=self.tokenizer.pad_token_id, eos_token_id=self.tokenizer.eos_token_id) File "/Users/chenyizhou/opt/anaconda3/envs/open_prompt/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "/Users/chenyizhou/opt/anaconda3/envs/open_prompt/lib/python3.8/site-packages/transformers/generation_utils.py", line 1083, in generate inputs_tensor, model_input_name, model_kwargs = self._prepare_model_inputs(inputs, bos_token_id, model_kwargs) File "/Users/chenyizhou/opt/anaconda3/envs/open_prompt/lib/python3.8/site-packages/transformers/generation_utils.py", line 401, in _prepare_model_inputs input_name = self.main_input_name File "/Users/chenyizhou/opt/anaconda3/envs/open_prompt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in **getattr** raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'PromptForGeneration' object has no attribute 'main_input_name'
> 
> Environment: openprompt==0.1.2 torch==1.11.0 no gpu (use_gpu==False) arguments: Namespace(lr=5e-05, model='t5', model_name_or_path='t5-base', plm_eval_mode=False)

Didn't meet the bug myself, seems like a PyTorch version issue. You can fix the bug by referring to the ``requirements.txt`` file.

<img width="947" alt="image" src="https://user-images.githubusercontent.com/17723822/164183296-4840acbc-08f4-4775-b528-aa989a484284.png">
