### ISSUE TITLE
Multiple mask

### ISSUE THREAD

**Issue by wulidongdong** [thunlp/OpenPrompt#146]
In generation_verbalizer.py, there is an example says that we can define a multiple-mask template and verbalizer:

```
    >>> input_example = InputExample(text_a = "Can fish run?", meta={"answer":"no", "explanation": "The fish have no legs"}, label=0)
    >>> template = "{'placeholder':'text_a'} answer: {'mask'} explanation: {'mask'}"
    The verbalizer can be:
    >>> label_words = {0:["no", "{'meta':'explanation'}"], 1:["yes", "{'meta':'explanation'}"]}
    >>> verbalizer = GenerationVerbalizer(tokenizer, classes=None, is_rule=True, label_words=label_words)
```

however, in the on_label_words_set function (in generation_verbalizer.py 102-115 [link),](https://github.com/thunlp/OpenPrompt/blob/cefc3be2a46f7b5c49089163483ffc1d8180c303/openprompt/prompts/generation_verbalizer.py#L102) it seems like only the first element of each class (i.e., no and yes in this case) would be pass into the self.label_words:

```
        if isinstance(self.label_words[0], list):
            self.label_words = [x[0] for x in self.label_words]
```
In this case, the tgt_text will only contain the first element, then it would raise an error when constructing data_loader:
```
tokenizing: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "prompt_learning_5-2-2-1.py", line 135, in <module>
    truncate_method="tail")
  File "/home/cike/anaconda3/envs/logic2nl/lib/python3.6/site-packages/openprompt/pipeline_base.py", line 101, in __init__
    self.tokenize()
  File "/home/cike/anaconda3/envs/logic2nl/lib/python3.6/site-packages/openprompt/pipeline_base.py", line 137, in tokenize
    inputfeatures = InputFeatures(**self.tokenizer_wrapper.tokenize_one_example(wrapped_example, self.teacher_forcing), **wrapped_example[1]).to_tensor()
  File "/home/cike/anaconda3/envs/logic2nl/lib/python3.6/site-packages/openprompt/plms/seq2seq.py", line 77, in tokenize_one_example
    print(tgt_text[num_mask_token_used])
IndexError: list index out of range
```

I am not familiar with prompt learning, What do I miss? Can you help me out please?
Thanks a lot.

**Comment by EshaanT** [comment]
@wulidongdong found any solution to this problem?

**Comment by ningding97** [comment]
It seems ok when I construct the dataloader in this example:

```python
plm, tokenizer, model_config, WrapperClass = load_plm('t5', 't5-base')
dataset= [InputExample(text_a = "Can fish run?", meta={"answer":"no", "explanation": "The fish have no legs"}, label=0)]
template = MixedTemplate(model=plm, tokenizer=tokenizer, text="{'placeholder':'text_a'} answer: {'mask'} explanation: {'mask'}")
label_words = {0:["no", "{'meta':'explanation'}"], 1:["yes", "{'meta':'explanation'}"]}
verbalizer = GenerationVerbalizer(tokenizer, classes=None, is_rule=True, label_words=label_words)
dataloader = PromptDataLoader(dataset=dataset, template=template, verbalizer=verbalizer, tokenizer=tokenizer,  tokenizer_wrapper_class=WrapperClass, max_seq_length=480, decoder_max_length=3, teacher_forcing=False, predict_eos_token=False, truncate_method="tail")
```

**Comment by EshaanT** [comment]
Wouldn't setting the **teacher_forcing** parameter (of PromptDataLoader) as **False** make the take difficult to learn for the generative model?
