### ISSUE TITLE
chinese-roberta-wwm-ext-large 中文roberta模型

### ISSUE THREAD

**Issue by Trevo1** [thunlp/OpenPrompt#251]
作者你好，我这边使用
`plm, tokenizer, model_config, WrapperClass = load_plm("roberta", "hfl/chinese-roberta-wwm-ext-large")`就会报错
`You are using a model of type bert to instantiate a model of type roberta. This is not supported for all configurations of models and can yield errors.
Some weights of the model checkpoint at hfl/chinese-roberta-wwm-ext-large were not used when initializing RobertaForMaskedLM: ['bert.encoder.layer.13.output.dense.bias', 'bert.encoder.layer.10.attention.self.value.weight', 'bert.encoder.layer.6.attention.self.key.bias', 'bert.encoder.layer.7.attention.self.key.weight', 'bert.encoder.layer.10.attention.self.value.bias', 'bert.encoder.layer.12.output.dense.bias', 'bert.encoder.layer.19.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.self.value.bias', 'bert.encoder.layer.10.attention.self.key.bias', 'bert.encoder.layer.18.output.dense.bias', 

Some weights of RobertaForMaskedLM were not initialized from the model checkpoint at hfl/chinese-roberta-wwm-ext-large and are newly initialized: ['encoder.layer.10.output.LayerNorm.weight', 'encoder.layer.15.intermediate.dense.bias', 'encoder.layer.19.attention.self.value.weight',

`
最后
`Traceback (most recent call last):
  File "stage3_prompt.py", line 17, in <module>
    plm, tokenizer, model_config, WrapperClass = load_plm("roberta", "hfl/chinese-roberta-wwm-ext-large")
  File "/home/nlpc/miniconda3/envs/pytorch-fcy/lib/python3.7/site-packages/openprompt/plms/__init__.py", line 103, in load_plm
    tokenizer = model_class.tokenizer.from_pretrained(model_path)
  File "/home/nlpc/miniconda3/envs/pytorch-fcy/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1791, in from_pretrained
    **kwargs,
  File "/home/nlpc/miniconda3/envs/pytorch-fcy/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1929, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/nlpc/miniconda3/envs/pytorch-fcy/lib/python3.7/site-packages/transformers/models/roberta/tokenization_roberta.py", line 222, in __init__
    with open(vocab_file, encoding="utf-8") as vocab_handle:
TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by Trevo1** [comment]
然后按照其他issue添加plms._MODEL_CLASSES['roberta'].tokenizer = RobertaTokenizer，也会报错
`Traceback (most recent call last):
  File "stage3_prompt.py", line 15, in <module>
    plms._MODEL_CLASSES['roberta'].tokenizer = RobertaTokenizer
AttributeError: can't set attribute`

**Comment by Trevo1** [comment]
> 

感谢作者，最后发现chinese-roberta-wwm-ext-large其实是用BertTokenizer。

还有问题就是使用openprompt该怎么输入多个模板呢，我看文档基本都是一个任务一个模板的例子，但是一个模板并不能很好的覆盖到大部分数据集🤦‍♂️

**Comment by Trevo1** [comment]
创建一个模板文件ManualTemplate.txt，然后像这样导入的话text = ManualTemplate.from_file(path='ManualTemplate.txt')
会提示我TypeError: from_file() missing 1 required positional argument: 'self'
from_file这个函数我看的是from_file(path: [str], choice: [int] = 0) 这是默认只导入第一行的模板吗，我的意思是能不能在同一个任务中使用我这个txt文件中的所有自定义好的模板

**Comment by Trevo1** [comment]
好的，看来是我搞错了，那就只能同时使用一个模板了

再次感谢！
