### ISSUE TITLE
Generation task with t5

### ISSUE THREAD

**Issue by puraminy** [thunlp/OpenPrompt#27]
It would be good if you put examples for t5.

I tried an my own task with t5 and I got:

```
Traceback (most recent call last):
  File "cli.py", line 181, in <module>
    main()
  File "cli.py", line 170, in main
    runner.run()
  File "/home/pouramini/OpenPrompt/openprompt/trainer.py", line 76, in run
    total_loss = self.train_epoch(epoch)
  File "/home/pouramini/OpenPrompt/openprompt/trainer.py", line 507, in train_epoch
    loss = self.prompt_model(batch).mean()  #TODO：unbanlanced batch chunks
  File "/home/pouramini/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pouramini/OpenPrompt/openprompt/pipeline_base.py", line 372, in forward
    return self._forward(*args, **kwargs)
  File "/home/pouramini/OpenPrompt/openprompt/pipeline_base.py", line 385, in _forward
    outputs = self.prompt_model(batch)
  File "/home/pouramini/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pouramini/OpenPrompt/openprompt/pipeline_base.py", line 176, in forward
    outputs =  self.model(**input_batch)
  File "/home/pouramini/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pouramini/transformers/src/transformers/models/t5/modeling_t5.py", line 1571, in forward
    encoder_outputs = self.encoder(
  File "/home/pouramini/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pouramini/transformers/src/transformers/models/t5/modeling_t5.py", line 1003, in forward
    layer_outputs = layer_module(
  File "/home/pouramini/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pouramini/transformers/src/transformers/models/t5/modeling_t5.py", line 639, in forward
    self_attention_outputs = self.layer[0](
  File "/home/pouramini/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pouramini/transformers/src/transformers/models/t5/modeling_t5.py", line 546, in forward
    attention_output = self.SelfAttention(
  File "/home/pouramini/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pouramini/transformers/src/transformers/models/t5/modeling_t5.py", line 503, in forward
    position_bias = position_bias + mask  # (batch_size, n_heads, seq_length, key_length)
RuntimeError: The size of tensor a (160) must match the size of tensor b (165) at non-singleton dimension 3
```

The task runs with `gpt2` however.

Also here is configuration:

```
dataset:
  name: atomic
  path: /home/pouramini/atomic/

task: generation

train:
  num_epochs: 3
  batch_size: 16
  teacher_forcing: True
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0

dataloader:
  max_seq_length: 160

environment:
  num_gpus: 1
  cuda_visible_devices:
generation: # Adding any arguments for generation here.
  parent_config: task
  max_length: 320

plm:
  model_name: t5
  model_path: /home/pouramini/pret/t5-base
  optimize:
    freeze_para: True

## LEARINING SETTING  ####################################################
learning_setting: full # selecting from "full", "zero_shot", "few_shot"

# few_shot:
#   parent_config: learning_setting
#   few_shot_sampling: sampling_from_train
reproduce:  # seed for reproduction 
  seed: 100

template: prefix_tuning_template
verbalizer:

prefix_tuning_template:
  parent_config: template
  text:
  mask_token: <mask>
  num_token: 5
  placeholder_mapping:
    <text_a>: text_a
    <text_b>: text_b
  prefix_dropout: 0.0
  mid_dim: 512
  optimize:
    name: AdamW
    lr: 0.00005
    betas:
      - 0.9
      - 0.999
    eps: 1.0E-8
    scheduler:
      num_warmup_steps: 0


```

**Comment by ShengdingHu** [comment]
PrefixTuning has fully support T5 now (may be combined with DataParallel will still yield bugs), and the performance bug when using gpt2 has also been fixed. Please try tutorial/2.x_conditional_generation.py
