### ISSUE TITLE
Failed to run the demo in `tutorial`

### ISSUE THREAD

**Issue by huchinlp** [thunlp/OpenPrompt#34]
command:
`python tutorial/1.1_mixed_template.py`

output:

```
  File "tutorial/1.1_mixed_template.py", line 94, in <module>
    logits = prompt_model(inputs)
  File "/home/h/anaconda3/envs/openprompt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/h/work/OpenPrompt/openprompt/pipeline_base.py", line 241, in forward
    outputs = self.verbalizer.gather_outputs(outputs)
TypeError: gather_outputs() takes 1 positional argument but 2 were given
```

**Comment by TheMrYang** [comment]
the same problem as me

**Comment by 161220012** [comment]
because gather_outputs() function needs an argument "self", which is missed

**Comment by ShengdingHu** [comment]
Thanks! It's a careless mistake in the last commit. We will fix it soon!

**Comment by TheMrYang** [comment]
> because gather_outputs() function needs an argument "self", which is missed
modify then another probelm
Traceback (most recent call last):
  File "experiments/cli.py", line 199, in <module>
    main()
  File "experiments/cli.py", line 69, in main
    test_dataset = test_dataset,
  File "experiments/cli.py", line 194, in trainer
    res = runner.run()
  File "./openprompt/trainer.py", line 358, in run
    self.fit(ckpt)
  File "./openprompt/trainer.py", line 338, in fit
    continue_training = self.training_epoch(self.cur_epoch)
  File "./openprompt/trainer.py", line 293, in training_epoch
    loss = self.training_step(batch, batch_idx)
  File "./openprompt/trainer.py", line 428, in training_step
    logits = self.model(batch)
  File "/mnt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "./openprompt/pipeline_base.py", line 247, in forward
    label_words_logits = self.verbalizer.process_outputs(outputs_at_mask, batch=batch)
  File "./openprompt/prompt_base.py", line 491, in process_outputs
    return self.process_logits(outputs, batch, **kwargs)
TypeError: process_logits() takes 2 positional arguments but 3 were given

**Comment by 161220012** [comment]
The same problem as me. Actually you will find that process_logits() has no declaraton. I do not know whether it leaves us to implement.

**Comment by Doragd** [comment]
Those bugs have been fixed in `branch:dev`.

**Comment by ShengdingHu** [comment]
Fixed！ Thanks！
