### ISSUE TITLE
run boolq_bert_large_cased_softprompt.yaml error

### ISSUE THREAD

**Issue by TheMrYang** [thunlp/OpenPrompt#35]
Traceback (most recent call last):
  File "experiments/cli.py", line 199, in <module>
    main()
  File "experiments/cli.py", line 69, in main
    test_dataset = test_dataset,
  File "experiments/cli.py", line 194, in trainer
    res = runner.run()
  File "./openprompt/trainer.py", line 358, in run
    self.fit(ckpt)
  File "./openprompt/trainer.py", line 338, in fit
    continue_training = self.training_epoch(self.cur_epoch)
  File "./openprompt/trainer.py", line 293, in training_epoch
    loss = self.training_step(batch, batch_idx)
  File "./openprompt/trainer.py", line 428, in training_step
    logits = self.model(batch)
  File "/mnt/yanghao/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "./openprompt/pipeline_base.py", line 245, in forward
    outputs = self.verbalizer.gather_outputs(outputs)
TypeError: gather_outputs() takes 1 positional argument but 2 were given

**Comment by ShengdingHu** [comment]
We will fix it soon. Thanks!

**Comment by ShengdingHu** [comment]
Fixed！
