### ISSUE TITLE
bug: AttributeError: 'T5ForConditionalGeneration' object has no attribute 'roberta'

### ISSUE THREAD

**Issue by hengfanz** [thunlp/OpenPrompt#39]
Token indices sequence length is longer than the specified maximum sequence length for this model (519 > 512). Running this sequence through the model will result in indexing errors
tokenizing: 250it [00:00, 374.45it/s]
Parameter containing:
tensor([[[4273]],

        [[ 150]],

        [[2087]]])
tensor([[-1.4704, -0.4191, -2.1847],
        [-1.4162, -0.7810, -1.2059]])
Traceback (most recent call last):
  File "/workspace/knowledgegraphcommon/business/text_classification/prompt/tutorial/0_basic.py", line 136, in <module>
    logits = prompt_model(inputs)
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/OpenPrompt/openprompt/pipeline_base.py", line 266, in forward
    outputs = self.prompt_model(batch)
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/OpenPrompt/openprompt/pipeline_base.py", line 186, in forward
    input_batch['inputs_embeds'] = self.plm.roberta.embeddings.word_embeddings(input_batch['input_ids'])
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'T5ForConditionalGeneration' object has no attribute 'roberta'

**Comment by hengfanz** [comment]
![image](https://user-images.githubusercontent.com/6941820/140728940-d28052ac-920b-44f7-a498-90e493db9005.png)
..   embarassment  尴尬，。,建议有test类覆盖，没有被测试的代码都是有bug的
