### ISSUE TITLE
SoftVerbalizer error

### ISSUE THREAD

**Issue by gaoisbest** [thunlp/OpenPrompt#78]
I am doing a Chinese sentiment analysis task, refer to tutorial [1.2_soft_verbalizer](https://github.com/thunlp/OpenPrompt/blob/main/tutorial/1.2_soft_verbalizers.py), 

I defined 
`prompt_verbalizer = SoftVerbalizer(tokenizer, plm, num_classes=2, label_words=['负面', '否定', '差的', '假的', '不', '正面', '肯定', '好的', '真的', '很'])`, 

but it gives the following log and raise a error:

```
Label word for a class is a list, only use the first word.                                                                                                                          
Word  负面 is split into multiple tokens: ['负', '面'].                     If this is not what you expect, try using another word for this verbalizer                                  
....
                                                                                                                     
Traceback (most recent call last):                                                                                                                                                  
  File "3_Soft_verbalizer_train.py", line 63, in <module>                                                                                                                           
    prompt_verbalizer = SoftVerbalizer(tokenizer, plm, num_classes=2, label_words=['负面', '否定', '差的', '假的', '不', '正面', '肯定', '好的', '真的', '很'])                                       
  
  File "/home/.conda/envs/few_shot/lib/python3.6/site-packages/openprompt-0.1.2-py3.6.egg/openprompt/prompts/soft_verbalizer.py", line 156, in generate_parameters          
AttributeError: 'Tensor' object has no attribute 'weight'           
```                                                                                                                

when I remove `label_words`, there is no error

**Comment by ShengdingHu** [comment]
Sorry, but we can't replicate the error.
